T=("January","February","March","April","May","June","July","August","September","October","November","December")
(a,b,c,z,m,k,l,j,h,f,d,s)=T
n=str(input("Введіть місяць"))
v=str(input("Введіть місяць"))
x=str(input("Введіть місяць"))
q=str(input("Введіть місяць"))
p=str(input("Введіть місяць"))
y=str(input("Введіть місяць"))
t=str(input("Введіть місяць"))
u=str(input("Введіть місяць"))
r=str(input("Введіть місяць"))
e=str(input("Введіть місяць"))
i=str(input("Введіть місяць"))
o=str(input("Введіть місяць"))
A={a:n,b:v,c:x,z:q,m:p,k:y,l:t,j:u,h:r,f:e,d:i,s:o}
print(A)
